### ISSUE TITLE
Missing Certs

### ISSUE THREAD

**Issue by agerlach** [123marvin123/typst-docker#1]
v0.11 seems to require certs to download packages that are not included in the image. Adding `ca-certificates` in the image fixes the issue. I would make a PR, but I am not clear how to add it in a barebones way w/ a builder.

**Comment by 123marvin123** [comment]
Thanks, I added the ca-certificates package to the image. It's rebuilding now and should be pushed automatically.

**Comment by agerlach** [comment]
Thank you for such a quick fix.
