### ISSUE TITLE
Release with typst 0.11.1

### ISSUE THREAD

**Issue by lukasjuhrich** [123marvin123/typst-docker#3]
Thank you for providing the image, I have been using it for my thesis all the time so far.

As of today, [typst 0.11.1](https://github.com/typst/typst/releases/tag/v0.11.1) has been released.
It includes some important fixes for me, I would be really glad if the image could be rebuilt any time in the next two weeks.

Cheers!

**Comment by 123marvin123** [comment]
Thanks, the image is being built automatically now and will be pushed to the Docker hub. It should be online in <2 hours, probably.
